### ISSUE TITLE
Doesn't work well with CubeNavigationController

### ISSUE THREAD

**Issue by 860969446** [andresbrun/ABCustomUINavigationController#13]
It seems that the demo does not work well( have no effect ) when using ' CubeNavigationController ' .
Can you please help?

in <AppDelegate.m>
//This works well , awesome !
    self.window.rootViewController = [[FlipSquaresNavigationController alloc] initWithRootViewController:self.viewController];

//But this does not ,when change to use the code below , Black screen was occurred after press push button
//    self.window.rootViewController = [[CubeNavigationController alloc] initWithRootViewController:self.viewController];

**Comment by andresbrun** [comment]
Yes, you are totally right :S. It has to be an issue with iOS8. I will take a look of it as soon as I can ;)

**Comment by andresbrun** [comment]
It should work now :)
