### ISSUE TITLE
Glitch on iPhone 6/6+

### ISSUE THREAD

**Issue by andresbrun** [andresbrun/ABCustomUINavigationController#18]
`snapshotAfterScreenUpdates:YES` is creating an small glitch before every transition on iPhones 6 and 6+. It is described as a Apple library issue so the solution has to be a workaround.

**Comment by HellowjingQiu** [comment]
its a bad news = =

**Comment by andresbrun** [comment]
With last SDK and using a different approach this is not longer an issue :)
