### ISSUE TITLE
UITransitionContextToViewKey and UITransitionContextFromViewKey are only available from ios8

### ISSUE THREAD

**Issue by xinwo** [andresbrun/ABCustomUINavigationController#19]
Hi,

UITransitionContextToViewKey and UITransitionContextFromViewKey are only available from ios8.
so this library only works on ios8 and later?

**Comment by andresbrun** [comment]
Nice catch, I've refactored completely this component one week ago, I didn't realise of that. I will change it to support iOS7 as soon as possible. Basically the change would be using:
```
[transitionContext viewControllerForKey:UITransitionContextFromViewControllerKey].view
```
but I need to test is everything work properly.

**Comment by xinwo** [comment]
Thank you for your quick reply

**Comment by andresbrun** [comment]
I've already added support to iOS 7, It is in the version 1.2.1. Thanks for let me know!
