### ISSUE TITLE
Would like directions using the library in Swift

### ISSUE THREAD

**Issue by pktrkts** [andresbrun/ABCustomUINavigationController#20]
Hi,

It's a bit unclear how to use the library in a Swift environment.  Would you post directions on how to use it in that situation?  It looks fairly straightforward to use in Objective C, but a lot of people are using Swift now, and it would be nice to be able to use your library in Swift.  Thanks.

Sincerely,
Sean

**Comment by andresbrun** [comment]
That's a very good point. I will update it soon adding compatibility with Swift and some examples ;)

**Comment by andresbrun** [comment]
The repo has been updated using the last SDK and some bugs have been fixed also. The usage in Swift is very similar to the usage in Objective-C, I have added it in the README. You can check https://github.com/andresbrun/ABCustomUINavigationController/tree/1.2.2
