### ISSUE TITLE
Trouble getting the cube navigation control working in Swift

### ISSUE THREAD

**Issue by pktrkts** [andresbrun/ABCustomUINavigationController#21]
Hi,

I've implemented your cube navigation controller just like in the demo.  It seems like the software is written so it will be used throughout the software, not just in a portion of the software- is this correct?  In the AppDelegate file I have:

var navigationController: CubeNavigationController!

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool
    {
        loadData()
        let myViewController = ViewController(nibName: "ViewController", bundle: nil)
        navigationController = CubeNavigationController(rootViewController: myViewController)
        return true
    }

Then in the initial viewcontroller I have:  

   @IBAction func segueToCreateNew(_ sender: UIButton)
    {
        var createNewAccountViewController = NewAccountCreationViewController(nibName: "NewAccountCreationViewController", bundle: nil)
        self.navigationController?.pushViewController(createNewAccountViewController, animated: true)
    }

This doesn't seem to work.  What am I doing wrong?

Thanks,
Sean

**Comment by andresbrun** [comment]
Hi pktrkts,

what exactly doesn't work? the animation is the default one? Or the viewcontroller doesn't even appear?

the only thing I see wrong in your piece of code is that you are not setting the 

``` swift
self.windows.rootViewController = CubeNavigationController(rootViewController: myViewController)
self.window.makeKeyAndVisible()
```
