### ISSUE TITLE
Why does the software behave differently in the app than in the demo software?

### ISSUE THREAD

**Issue by pktrkts** [andresbrun/ABCustomUINavigationController#22]
Hi,

So, I'm very happy with how the push functions work.  They look exactly the same as the demo.  However, the pop functions don't look at all the same in behavior.  We like how the demo behaves.  We don't like how the library pop functions behave in our software.  Would you be willing to fix the library so that the behavior of the library (the pod) matches the behavior of the demo?

Let me know if you need a video of the behavior so we can further clarify what we are talking about.

Thanks,
Sean

**Comment by andresbrun** [comment]
Hi pktrkts,

thanks for your patience, could you send me a gif or video showing how it behaves the pop to you? I will try to find some time to fix it as soon as possible :)

**Comment by pktrkts** [comment]
![animation](https://cloud.githubusercontent.com/assets/19662843/22394712/2976aa3e-e4dc-11e6-8e47-071ef4f082f7.gif)

Sorry it took so long to get back to you.  Does this answer your question?

**Comment by pktrkts** [comment]
Hi,

It has been 20 days since I left the video comment.  Any progress made yet?

Sincerely,
Sean

**Comment by andresbrun** [comment]
Yeah... sorry about that, it is being very busy days, I haven't investigate it si far. You can try to fix by your own and create a PR with it because I don't think I can work on it until end of next week at least.
Best, Andrés 

Get Outlook for iOS




On Fri, Feb 17, 2017 at 6:29 AM +0100, "pktrkts" <notifications@github.com> wrote:












Hi,


It has been 20 days since I left the video comment.  Any progress made yet?


Sincerely,

Sean

**Comment by pktrkts** [comment]
Hello,

Thank you for getting back to me.  At the moment we've got some time before we intend to release our software, so we'll wait for you to fix this (assuming, should we wait, that you will fix it- I'm aware that that is not a given, but it sounds like you are willing to fix it but need some time).  If I were to try to fix this particular problem, it would take a sizable chunk of time, because I don't know Objective C (just Swift), and I'm not particularly familiar with writing my own animations.  If you don't think you will get around to it, say within the next month or so, then we'll probably look at using someone else's library that works out of the box the way we want.  No offense- in general your library works beautifully and we are grateful for the effort you invested in this tool.  However, my partner is pretty dissatisfied with how the pop actually works in our software, and he really desires something that works closer to how your demo works.  Will you be able to get around to fixing this bug, say in the next month or so?

Sincerely,
Sean

**Comment by andresbrun** [comment]
Hi Sean, I've finally got some time to take a look of this issue. Right now the demo project works as expected (push and pop). I have tried in iPhone and iPad. I am gonna need more info to solve this issue. Is it happening in all iOS versions? Can you recreate the issue in a small project and send it back to me?

**Comment by pktrkts** [comment]
Hi Andres, it turns out that the problem was somehow on our end.  Through chance I discovered that the problem went away when I used a new project file.  Somehow, the file must have got corrupted.  Don't ask me how- this makes no sense at all to me.  All I know, with a new project file the pop works just fine.  Thanks for your assistance!
